# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-29 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualUrl', models.URLField(max_length=1024)),
                ('shortURL', models.URLField(max_length=1024)),
            ],
        ),
    ]
